version: '3.8'

services:
  spark-yarn-master:
    container_name: spark-yarn-master
    build:
      dockerfile: Dockerfile-yarn
      context: .
    image: spark-yarn-image
    entrypoint: ['./entrypoint.sh', 'master']
    volumes:
      - ./data:/opt/spark/data
      - ./spark-scripts:/opt/spark/spark-scripts
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '9870:9870'
      - '7077:7077'
      - '8088:8088'


  spark-yarn-worker:
    container_name: spark-yarn-worker
    image: spark-yarn-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-yarn-master
    env_file:
      - .env.spark
    volumes:
      - ./data:/opt/spark/data
      - ./spark-scripts:/opt/spark/spark-scripts

  yarn-history-server:
    container_name: spark-yarn-history
    image: spark-yarn-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-yarn-master
    env_file:
      - .env.spark
    ports:
      - '18080:18080'