version: '3.8'

services:
  spark-yarn-master:
    image: spark-yarn-image
    container_name: spark-yarn-master
    entrypoint: ['./entrypoint.sh', 'master']
    volumes:
      - ./data:/opt/spark/data
      - ./spark-scripts:/opt/spark/spark-scripts
    ports:
      - '9090:8080'
      - '9870:9870'
      - '7077:7077'
      - '8088:8088'

  spark-yarn-worker:
    image: spark-yarn-image
    container_name: spark-yarn-worker
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-yarn-master
    volumes:
      - ./data:/opt/spark/data
      - ./spark-scripts:/opt/spark/spark-scripts

  spark-yarn-history:
    image: spark-yarn-image
    container_name: spark-yarn-history
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-yarn-master
    ports:
      - '18080:18080'